# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  riverrunnerwebapi:
    image: riverrunnerwebapi
    build:
      context: .
      dockerfile: src/Web/Api/Dockerfile
    ports:
      - 5666:5666
